# See https://docs.sourcegraph.com/dev/background-information/ci#pr-auditor
name: pr-auditor
on:
  pull_request_target:
    types: [ closed, edited, opened, synchronize, ready_for_review ]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          repository: 'sourcegraph/pr-auditor'
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
        with: { go-version: '1.20' }

      - run: './check-pr.sh'
        env:
          GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
